enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

packageExtensions:
  "@gardener-dashboard/backend@*":
    dependencies:
      openapi-types: "*"
  # vitest uses local-pkg to indirectly and dynamically (depending on test config) access dependant
  # packages. The accessed packages are not listed as dependency of local-pkg which causes yarn to error.
  local-pkg@*:
    dependencies:
      "@vitest/coverage-c8": "*"
      jsdom: "*"
  "@vuetify/loader-shared@*":
    dependencies:
      vue: "*"


plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/holgerkoser/yarn-contrib/-/raw/1.0.0-beta.3/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.4.1.cjs
